# Generated by Django 3.2.6 on 2021-09-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('carbohydrate', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('fat_ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('carb_ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('protein_ratio', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
