# Generated by Django 3.2.6 on 2021-09-17 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20210916_0534'),
        ('fooddb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='FoodDb',
        ),
    ]
