# Generated by Django 3.2.6 on 2021-09-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddb', '0002_auto_20210929_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='carb_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='food',
            name='serving_size',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
