# Generated by Django 3.2.6 on 2021-09-17 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20210916_0534'),
        ('fooddb', '0002_rename_food_fooddb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodDb',
            new_name='Food',
        ),
    ]
