# Generated by Django 3.2.6 on 2021-10-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddb', '0003_auto_20210930_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='salt',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
