# Generated by Django 3.1.5 on 2021-08-27 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mealDate', models.DateField()),
                ('meal', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=30, null=True)),
                ('fat', models.PositiveIntegerField(null=True)),
                ('carbohydrate', models.PositiveIntegerField(null=True)),
                ('protien', models.PositiveIntegerField(null=True)),
                ('calories', models.PositiveIntegerField(null=True)),
                ('fat_ratio', models.IntegerField()),
                ('carb_ratio', models.IntegerField()),
                ('protein_ratio', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.DateField()),
                ('total_calories', models.PositiveIntegerField(null=True)),
                ('fat_ratio', models.IntegerField()),
                ('carb_ratio', models.IntegerField()),
                ('protein_ratio', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
