# Generated by Django 3.1.5 on 2021-08-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='fat',
            new_name='fats',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='protien',
            new_name='protein',
        ),
    ]
