# Generated by Django 3.2.6 on 2021-08-30 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20210829_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('-mealDate',)},
        ),
    ]
