# Generated by Django 3.2.6 on 2021-09-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20210908_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='serving',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
