# Generated by Django 3.2.6 on 2021-09-13 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_food_serving'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='mealDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
