# Generated by Django 3.2.6 on 2021-09-16 05:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fooddb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0007_auto_20210913_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyfood',
            old_name='total_calories',
            new_name='daily_calories',
        ),
        migrations.RenameField(
            model_name='dailyfood',
            old_name='carb_ratio',
            new_name='daily_carb_ratio',
        ),
        migrations.RenameField(
            model_name='dailyfood',
            old_name='fat_ratio',
            new_name='daily_fat_ratio',
        ),
        migrations.RenameField(
            model_name='dailyfood',
            old_name='protein_ratio',
            new_name='daily_protein_ratio',
        ),
        migrations.AlterField(
            model_name='dailyfood',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TestFood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mealDate', models.DateField(default=datetime.datetime.now)),
                ('meal', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=30, null=True)),
                ('serving', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fooddb.food')),
            ],
            options={
                'ordering': ('-mealDate',),
            },
        ),
    ]
