# Generated by Django 3.2.6 on 2021-10-07 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fooddb', '0004_alter_food_salt'),
        ('food', '0008_auto_20210916_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='carb_ratio',
        ),
        migrations.RemoveField(
            model_name='food',
            name='carbohydrate',
        ),
        migrations.RemoveField(
            model_name='food',
            name='fat_ratio',
        ),
        migrations.RemoveField(
            model_name='food',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='food',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='food',
            name='name',
        ),
        migrations.RemoveField(
            model_name='food',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='food',
            name='protein_ratio',
        ),
        migrations.AddField(
            model_name='food',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fooddb.food'),
        ),
        migrations.DeleteModel(
            name='TestFood',
        ),
    ]
